modLoader="javafml"
loaderVersion="[40,)"
license="Apache-2.0"
issueTrackerURL="https://infernalstudios.org"

[[mods]]
modId = "spreadingmoss"
version="${file.jarVersion}"
displayName = "Spreading Moss"
# updateJSONURL="https://infernalstudios.org/api/mods/spreadingmoss/forge"
displayURL="https://infernalstudios.org"
# logoFile = ""
credits = "Infernal Studios"
authors = "Infernal Studios"
description = '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
'''

[[dependencies.spreadingmoss]]
  modId="forge"
  mandatory=true
  versionRange="[40,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.spreadingmoss]]
  modId="minecraft"
  mandatory = true
  versionRange = "[1.18.2,1.19)"
  ordering = "NONE"
  side="BOTH"